version: "3.8"

volumes:
  appDB:

networks:
  mysqlNET:
  appNET:

services:
  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - appDB:/var/lib/mysql 
    networks:
      - mysqlNET
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ROOT_HOST=%
      - bind-address:0.0.0.0
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - mysqlNET
      - appNET
    ports: 
      - 5000:80
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql

